### ISSUE TITLE
As a user, I would like to be able to subscribe to a performance, so that I will receive a notification from the app shortly before it starts.

### ISSUE THREAD

**Issue by aaron13michael** [OpenMic/DV#118]
Code to subscribe to a performance. We will use topics in FCM to do this. The topic for a performance will be it's ID.

**Comment by David-Egan** [comment]
Couldn't there be (super unlikely) id collision where we end up trying to make 2 topics with the same string? Whether thats feasible or not I think it'd be good if we made having a little prefix standard for example a topic could be structured like "perf-{ID}"
